#!/usr/bin/env ansible-playbook
## vim:ft=ansible :

---

- debug: msg="==> Setting PHP7 configure on CentOS system"

# Setting  PHP7.
- name: create socket directory for ceotns 6
  file: path=/run/php-fpm/ state=directory mode=0755
  when: ansible_distribution_major_version == "6"

- name: Disable port listen
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^listen = 127.0.0.1:9000' line=';listen = 127.0.0.1:9000'"
  notify: restart php7-fpm on centos

- name: Enable socket listen
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?listen = /run/php-fpm/www.sock' line='listen = /run/php-fpm/www.sock'"
  notify: restart php7-fpm on centos

- name: Set permissions on socket - owner
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?listen.owner' line='listen.owner = {{ php_owner }}'"
  notify: restart php7-fpm on centos

- name: Set permissions on socket - group
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?listen.group' line='listen.group = {{ php_group}}'"
  notify: restart php7-fpm on centos

- name: Set permissions on socket - mode
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?listen.mode' line='listen.mode = 0660'"
  notify: restart php7-fpm on centos

- name: Disable port upstream of php-fpm
  lineinfile: "dest=/etc/nginx/conf.d/php-fpm.conf state=present regexp='^        server 127.0.0.1:9000' line='        #server 127.0.0.1:9000'"
  notify: restart php7-fpm on centos

- name: Enable socket upstream of php-fpm
  lineinfile: "dest=/etc/nginx/conf.d/php-fpm.conf state=present regexp='^        #server unix:/run/php-fpm/www.sock;' line='        server unix:/run/php-fpm/www.sock;'"
  notify: restart php7-fpm on centos

- name: Set listen acl users
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?listen.acl_users = nginx' line='listen.acl_users = nginx'"
  notify: restart php7-fpm on centos

- name: Ensure timezone is set in fpm php.ini
  lineinfile: dest=/etc/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ php_timezone }}'

- name: Enabling opcache
  lineinfile: dest=/etc/php.ini
              regexp='^#?opcache.enable='
              line='opcache.enable=1'

- name: Opcache - changing revalidate frequency to 0
  lineinfile: dest=/etc/php.ini
              regexp='opcache.revalidate_freq='
              line='opcache.revalidate_freq=0'
  tags: [ development ]

- name: Set session.cookie_httponly to `true`
  lineinfile: dest=/etc/php.ini
              regexp='session.cookie_httponly(\s)?='
              line='session.cookie_httponly=1'
  notify: restart php7-fpm on centos

- name: Enable session strict mode
  lineinfile: dest=/etc/php.ini
              regexp='session.use_strict_mode(\s)?='
              line='session.use_strict_mode = 1'
  notify: restart php7-fpm on centos

- name: Disable url fopen
  lineinfile: dest=/etc/php.ini
              regexp='allow_url_fopen(\s)?='
              line='allow_url_fopen = Off'
  notify: restart php7-fpm on centos

- name: Change soap.wsdl_cache_dir to new directory
  lineinfile: dest=/etc/php.ini
              regexp='soap.wsdl_cache_dir(\s)?='
              line='soap.wsdl_cache_dir=/php/cache/wsdl'
  notify: restart php7-fpm on centos

- name: Change upload_tmp_dir path
  lineinfile: dest=/etc/php.ini
              regexp='upload_tmp_dir(\s)?='
              line='upload_tmp_dir=/php/cache/upload_tmp'
  notify: restart php7-fpm on centos

- name: Exclude potentially harmfull php functions
  lineinfile: dest=/etc/php.ini
              regexp='disable_functions(\s)?='
              line='disable_functions=exec,passthru,system,popen'
  notify: restart php7-fpm on centos

- name: Set post_max_size
  lineinfile: dest=/etc/php.ini
              regexp='post_max_size(\s)?='
              line='post_max_size = {{ php_post_max_size }}'
  notify: restart php7-fpm on centos

- name: Set upload_max_filesize
  lineinfile: dest=/etc/php.ini
              regexp='upload_max_filesize(\s)?='
              line='upload_max_filesize = {{ php_upload_max_filesize }}'
              create=yes
  notify: restart php7-fpm on centos

- name: Set memory_limit
  lineinfile: dest=/etc/php.ini
              regexp='memory_limit(\s)?='
              line='memory_limit = {{ php_memory_limit }}'
  notify: restart php7-fpm on centos

